version: "3"

services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306

  wp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST'] );
        define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST'] );
        define('WP_DEBUG_LOG', true);
    volumes:
      - ./.wordpress/wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wp-graphql-filter-query
    ports:
      - 8081:80
    depends_on:
      - db

# Make network name pretty

# Persist DB and WordPress data across containers
volumes:
  db-data:
  # wp-data:
